/* eslint-disable */
// Auto-generated by scripts/build_catalog.py — do not edit by hand.
window.PRODUCTS_DATA = {
  "sections": [
    {
      "id": "classic",
      "label": "Классические"
    },
    {
      "id": "homemade",
      "label": "Домашние торты"
    },
    {
      "id": "other",
      "label": "Другие торты"
    },
    {
      "id": "pastries",
      "label": "Пирожное"
    }
  ],
  "products": {
    "classic": [
      {
        "title": "Домашний",
        "slug": "domashniy",
        "description": "Классический белый бисквит в сочетании со взбитыми сливками.",
        "weights": [
          {
            "label": "0,7 кг",
            "price": "885 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Каприз",
        "slug": "kapriz",
        "description": "Классический белый бисквит прослоен взбитыми сливками с клубничным вкусом. Оформлен воздушным рисом.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "855 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Лавандовый",
        "slug": "lavandovyy",
        "description": "Лавандовый бисквит прослоен взбитыми сливками и конфитюром «Черника».",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 115 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Гороскоп",
        "slug": "goroskop",
        "description": "Песочные коржи в сочетании с шоколадным сливочно-белковым кремом.",
        "weights": [
          {
            "label": "0,85 кг",
            "price": "1 010 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Любимый",
        "slug": "lyubimyy",
        "description": "Песочные коржи в сочетании со сливочным кремом на основе варёного сгущённого молока.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "935 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 170 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Творожный счастливчик",
        "slug": "tvorozhnyy-schastlivchik",
        "description": "Классический белый бисквит с натуральным творогом в сочетании со взбитыми сливками.",
        "weights": [
          {
            "label": "0,7 кг",
            "price": "960 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Медовый",
        "slug": "medovyy",
        "description": "Коржи с натуральным мёдом прослоены сливочно-йогуртовым кремом.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 095 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Медовичок",
        "slug": "medovichok",
        "description": "Коржи с натуральным мёдом прослоены варёным сгущённым молоком.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "580 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Фиеста",
        "slug": "fiesta",
        "description": "Коржи с натуральным мёдом прослоены сливочным кремом на основе варёного сгущённого молока. Оформлен белковым кремом.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 210 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Забайкальская птичка",
        "slug": "zabaykalskaya-ptichka",
        "description": "Ванильно-сливочное суфле в сочетании с классическим белым бисквитом. Оформлен шоколадной глазурью.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "630 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false
      }
    ],
    "homemade": [
      {
        "title": "Восточная сказка",
        "slug": "vostochnaya-skazka",
        "description": "Слои шоколадного и белого бисквита на сметане и сгущённом молоке прослоены йогуртовым кремом и клубничным конфитюром.",
        "weights": [
          {
            "label": "0,55 кг",
            "price": "960 ₽"
          },
          {
            "label": "1,1 кг",
            "price": "1 515 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Оригинальный",
        "slug": "originalnyy",
        "description": "Слои шоколадного и белого бисквита на сметане и сгущённом молоке прослоены сметанным кремом.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 335 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Мокко",
        "slug": "mokko",
        "description": "Шоколадный бисквит на сметане и сгущённом молоке в сочетании со сливочно-шоколадным кремом.",
        "weights": [
          {
            "label": "0,65 кг",
            "price": "735 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Парижские тайны",
        "slug": "parizhskie-tayny",
        "description": "Белый бисквит на сметане и сгущённом молоке в сочетании со взбитыми сливками.",
        "weights": [
          {
            "label": "0,55 кг",
            "price": "725 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 260 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Земляничный десерт",
        "slug": "zemlenichnyy-desert",
        "description": "Белый бисквит на сметане и сгущённом молоке в сочетании со взбитыми сливками с земляничным вкусом.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 085 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Тирамису",
        "slug": "tiramisu",
        "description": "Слои белого бисквита на сметане и сгущённом молоке прослоены взбитыми сливками со вкусом кофе.",
        "weights": [
          {
            "label": "0,4 кг",
            "price": "620 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Прага",
        "slug": "praga",
        "description": "Бисквит на сметане и сгущённом молоке.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "760 ₽"
          },
          {
            "label": "1,1 кг",
            "price": "1 575 ₽"
          },
          {
            "label": "2,2 кг",
            "price": "2 835 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true,
        "note": "Ждём полное описание мамы (есть в другом письме)."
      },
      {
        "title": "Сакура",
        "slug": "sakura",
        "description": "Бисквит на сметане и сгущённом молоке.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "770 ₽"
          },
          {
            "label": "1,1 кг",
            "price": "1 400 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true,
        "note": "Ждём полное описание мамы."
      },
      {
        "title": "Идиллия",
        "slug": "idilliya",
        "description": "Бисквит на сметане и сгущённом молоке.",
        "weights": [
          {
            "label": "0,65 кг",
            "price": "820 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true,
        "note": "Ждём полное описание мамы."
      },
      {
        "title": "Чернослив в шоколаде",
        "slug": "chernosliv-v-shokolade",
        "description": "Бисквит на сметане и сгущённом молоке.",
        "weights": [
          {
            "label": "0,45 кг",
            "price": "685 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём полное описание мамы."
      },
      {
        "title": "С черносливом",
        "slug": "s-chersnoslivym",
        "description": "Бисквит на сметане и сгущённом молоке с черносливом.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "780 ₽"
          },
          {
            "label": "1,1 кг",
            "price": "1 460 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true,
        "note": "Ждём полное описание мамы."
      },
      {
        "title": "Чародейка",
        "slug": "charodeyka",
        "description": "Слои белого бисквита на сметане прослоены сливочным кремом. Оформлен кокосовой стружкой и гелем.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "735 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 285 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Черемуховый",
        "slug": "cheremukhovyy",
        "description": "Белый бисквит на сметане с добавлением молотой черёмухи в сочетании со сливочным кремом.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "760 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 260 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Вишневый",
        "slug": "vishnevyy",
        "description": "Шоколадный бисквит на сметане с добавлением молотой вишни прослоен сливочным кремом с вишнёвым конфитюром.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "925 ₽"
          },
          {
            "label": "1,1 кг",
            "price": "1 575 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Три желания",
        "slug": "tri-zhelaniya",
        "description": "Три разных бисквита на основе сгущённого молока с добавлением какао, грецкого ореха и мака в сочетании со сливочно-йогуртовым кремом.",
        "weights": [
          {
            "label": "0,55 кг",
            "price": "760 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 315 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Шоколадная девочка",
        "slug": "shokoladnaya-devochka",
        "description": "Слои масляного бисквита с какао прослоены взбитыми сливками с добавлением сливочно-сырного крема.",
        "weights": [
          {
            "label": "0,65 кг",
            "price": "1 050 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Клубничное чудо",
        "slug": "klubnichnoe-chudo",
        "description": "Слои масляного бисквита в сочетании со взбитыми сливками с клубничным вкусом.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 135 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false
      },
      {
        "title": "Изобилие",
        "slug": "izobilie",
        "description": "Масляный бисквит со сгущённым молоком с добавлением грецкого ореха прослоен сливочным кремом с кусочками чернослива.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "980 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 680 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      }
    ],
    "other": [
      {
        "title": "Красный бархат",
        "slug": "krasnyy-barhat",
        "description": "Бисквит «Красный бархат» со сливочно-сырным кремом.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "820 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 515 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true,
        "note": "Ждём описание и вес от мамы."
      },
      {
        "title": "Славутич",
        "slug": "slavutich",
        "description": "Медово-шоколадные коржи со сливочным кремом.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 230 ₽"
          },
          {
            "label": "1,5 кг",
            "price": "1 575 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание от мамы."
      },
      {
        "title": "Эльбрус",
        "slug": "elbrus",
        "description": "Бисквитный торт со сливочным кремом и воздушным безе.",
        "weights": [
          {
            "label": "0,9 кг",
            "price": "1 105 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание от мамы."
      },
      {
        "title": "Фисташковый",
        "slug": "fistashkovyy",
        "description": "Фисташковый бисквит со сливочным кремом.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 525 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание от мамы."
      },
      {
        "title": "Царский (банановый)",
        "slug": "tsarskiy-bananovyy",
        "description": "Царский торт с банановой начинкой.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "1 000 ₽"
          },
          {
            "label": "1,2 кг",
            "price": "1 705 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание и вес от мамы."
      },
      {
        "title": "Полёт-Премиум",
        "slug": "polet-premium",
        "description": "Воздушно-ореховое безе со сливочным кремом.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "970 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 890 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём полное описание от мамы."
      },
      {
        "title": "Полёт с кедровым орехом",
        "slug": "polet-kedrovyy",
        "description": "Воздушно-ореховое безе с кедровым орехом и сливочным кремом.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "1 285 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём полное описание от мамы."
      },
      {
        "title": "Полёт с варёным сгущённым молоком",
        "slug": "polet-varenka",
        "description": "Воздушно-ореховое безе со сливочным кремом на варёном сгущённом молоке.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "уточняйте"
          },
          {
            "label": "1,0 кг",
            "price": "уточняйте"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём полное описание от мамы."
      },
      {
        "title": "Полёт со сливочным кремом",
        "slug": "polet-slivochnyy",
        "description": "Воздушно-ореховое безе со сливочным кремом.",
        "weights": [
          {
            "label": "0,5 кг",
            "price": "885 ₽"
          },
          {
            "label": "1 кг",
            "price": "1 670 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём полное описание от мамы."
      },
      {
        "title": "Вишня со сливками",
        "slug": "vishnya-so-slivkami",
        "description": "Нежный бисквит с вишнёвой начинкой и воздушными сливками.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 030 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Курский",
        "slug": "kurskiy",
        "description": "Песочные коржи с нежной начинкой по традиционному рецепту.",
        "weights": [
          {
            "label": "0,9 кг",
            "price": "1 115 ₽"
          },
          {
            "label": "1,4 кг",
            "price": "1 725 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Элитный",
        "slug": "elitnyy",
        "description": "Бисквитный торт премиального уровня с изысканным кремом и декором.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 220 ₽"
          },
          {
            "label": "1,5 кг",
            "price": "1 785 ₽"
          },
          {
            "label": "2 кг",
            "price": "2 260 ₽"
          },
          {
            "label": "2,5 кг",
            "price": "2 835 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Чёрный Люкс",
        "slug": "chernyy-lyuks",
        "description": "Изысканный шоколадный торт премиум-класса с насыщенным вкусом и благородным оформлением.",
        "weights": [
          {
            "label": "1.3 кг",
            "price": "1 950 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Сникерс",
        "slug": "snikers",
        "description": "Шоколадный торт с карамелью, арахисом и нежным кремом.",
        "weights": [
          {
            "label": "0,9 кг",
            "price": "1 170 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Трюфельный",
        "slug": "tryufelnyy",
        "description": "Насыщенный шоколадный вкус с трюфельной начинкой и бархатистым кремом.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 040 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Праздничный",
        "slug": "prazdnichnyy",
        "description": "Яркий праздничный торт с праздничным декором для особых случаев.",
        "weights": [
          {
            "label": "2 кг",
            "price": "2 100 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Фантазия",
        "slug": "fantaziya",
        "description": "Праздничный торт с авторским декором и нежным кремом.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 170 ₽"
          },
          {
            "label": "1,5 кг",
            "price": "1 680 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Соблазн",
        "slug": "soblazn",
        "description": "Изысканный фирменный торт с насыщенным вкусом и элегантным оформлением.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "1 105 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false
      },
      {
        "title": "Царский",
        "slug": "tsarskiy",
        "description": "Премиальный торт с богатым декором и насыщенным вкусом.",
        "weights": [
          {
            "label": "0,6 кг",
            "price": "1 000 ₽"
          },
          {
            "label": "1,2 кг",
            "price": "1 705 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true
      },
      {
        "title": "Лакомка",
        "slug": "lakomka",
        "description": "Шоколадно-ореховый торт со сгущённым молоком.",
        "weights": [
          {
            "label": "1 кг",
            "price": "1 305 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": true,
        "note": "Ждём описание от мамы."
      }
    ],
    "pastries": [
      {
        "title": "Графские развалины",
        "slug": "grafskie-razvaliny",
        "description": "Крошка воздушного безе с орехом в сочетании со сливочным кремом с варёной сгущёнкой.",
        "weights": [
          {
            "label": "0,8 кг",
            "price": "840 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false
      },
      {
        "title": "Корзиночка",
        "slug": "korzinochka",
        "description": "Корзиночка из песочного теста, наполнена яблочным повидлом, украшена белковым кремом, консервированной вишней или желейной ягодой.",
        "weights": [
          {
            "label": "160 гр",
            "price": "265 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false
      },
      {
        "title": "Эклеры",
        "slug": "eklery",
        "description": "Заварное тесто с варёной сгущёнкой или белково-сливочным кремом.",
        "weights": [
          {
            "label": "50 гр",
            "price": "80-90 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false
      },
      {
        "title": "Кольцо заварное",
        "slug": "kolco-zavarnoe",
        "description": "Заварное кольцо.",
        "weights": [
          {
            "label": "30 гр",
            "price": "55 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание от мамы."
      },
      {
        "title": "Бисквитно-кремовое",
        "slug": "biskvitno-kremovoe",
        "description": "Бисквитно-кремовое пирожное.",
        "weights": [
          {
            "label": "0,375 кг",
            "price": "445 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание от мамы."
      },
      {
        "title": "Бисквитно-кремовое с суфле",
        "slug": "biskvitno-kremovoe-sufle",
        "description": "Бисквитно-кремовое пирожное с суфле.",
        "weights": [
          {
            "label": "0,450 кг",
            "price": "600 ₽"
          }
        ],
        "hasWhole": true,
        "hasCut": false,
        "note": "Ждём описание от мамы."
      }
    ],
    "cookies": []
  }
};
